version: '3'

services:

  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  django_api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: django_api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - mynetwork

  react_app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_app
    command: npm start
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
